"use client"
import React from 'react'
import { motion, useScroll, useSpring, useTransform } from "framer-motion"
const ScrollAnimations = () => {
    const { scrollYProgress } = useScroll();
    const scaleX = useSpring(scrollYProgress);
    const background = useTransform(scrollYProgress,[0, 1],["rgb(86,1,254)", "rgb(1, 25, 13)"]);
    return (
        <div className='w-full border border-border p-4 flex flex-col items-center gap-7'>
            <div className='w-full text-left'>
                <h2 className='text-3xl font-bold'>ScrollAnimations</h2>
            </div>
            <section>
                <motion.div
                    style={{
                        // scaleX: scrollYProgress,
                        scaleX: scaleX,
                        background,
                        transformOrigin: "left"
                    }}
                    className={`sticky top-0 w-full h-1`}
                >

                </motion.div>
                <div className='flex flex-col gap-7'>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Labore vitae expedita hic illo, deleniti officia quae quo laudantium? Ea modi, illum illo repellendus aspernatur excepturi dolores iusto laborum voluptatem esse, velit laudantium officia optio. Quia officia quaerat ipsam debitis rem odit quis dolorum quae iure, exercitationem rerum vero dolorem magni laborum impedit adipisci soluta facere mollitia reprehenderit nulla molestias sunt delectus quod corporis! Doloremque commodi suscipit est saepe dolor illo quas expedita optio tempora perferendis dolorum ipsam sit, dignissimos necessitatibus aspernatur ullam repellat corporis facere veritatis quod incidunt. Assumenda deleniti repellat nostrum veritatis! Aliquid quos iure consequuntur voluptate, enim animi labore. Accusantium eos quod, nulla voluptate assumenda doloremque possimus ex ut corrupti veritatis aut. Ut, commodi, nemo voluptatum cum beatae delectus facere, accusantium nulla officia reiciendis eos totam. Doloremque magni suscipit sint. Dolor, ut!</p>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Labore vitae expedita hic illo, deleniti officia quae quo laudantium? Ea modi, illum illo repellendus aspernatur excepturi dolores iusto laborum voluptatem esse, velit laudantium officia optio. Quia officia quaerat ipsam debitis rem odit quis dolorum quae iure, exercitationem rerum vero dolorem magni laborum impedit adipisci soluta facere mollitia reprehenderit nulla molestias sunt delectus quod corporis! Doloremque commodi suscipit est saepe dolor illo quas expedita optio tempora perferendis dolorum ipsam sit, dignissimos necessitatibus aspernatur ullam repellat corporis facere veritatis quod incidunt. Assumenda deleniti repellat nostrum veritatis! Aliquid quos iure consequuntur voluptate, enim animi labore. Accusantium eos quod, nulla voluptate assumenda doloremque possimus ex ut corrupti veritatis aut. Ut, commodi, nemo voluptatum cum beatae delectus facere, accusantium nulla officia reiciendis eos totam. Doloremque magni suscipit sint. Dolor, ut!</p>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Labore vitae expedita hic illo, deleniti officia quae quo laudantium? Ea modi, illum illo repellendus aspernatur excepturi dolores iusto laborum voluptatem esse, velit laudantium officia optio. Quia officia quaerat ipsam debitis rem odit quis dolorum quae iure, exercitationem rerum vero dolorem magni laborum impedit adipisci soluta facere mollitia reprehenderit nulla molestias sunt delectus quod corporis! Doloremque commodi suscipit est saepe dolor illo quas expedita optio tempora perferendis dolorum ipsam sit, dignissimos necessitatibus aspernatur ullam repellat corporis facere veritatis quod incidunt. Assumenda deleniti repellat nostrum veritatis! Aliquid quos iure consequuntur voluptate, enim animi labore. Accusantium eos quod, nulla voluptate assumenda doloremque possimus ex ut corrupti veritatis aut. Ut, commodi, nemo voluptatum cum beatae delectus facere, accusantium nulla officia reiciendis eos totam. Doloremque magni suscipit sint. Dolor, ut!</p>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Labore vitae expedita hic illo, deleniti officia quae quo laudantium? Ea modi, illum illo repellendus aspernatur excepturi dolores iusto laborum voluptatem esse, velit laudantium officia optio. Quia officia quaerat ipsam debitis rem odit quis dolorum quae iure, exercitationem rerum vero dolorem magni laborum impedit adipisci soluta facere mollitia reprehenderit nulla molestias sunt delectus quod corporis! Doloremque commodi suscipit est saepe dolor illo quas expedita optio tempora perferendis dolorum ipsam sit, dignissimos necessitatibus aspernatur ullam repellat corporis facere veritatis quod incidunt. Assumenda deleniti repellat nostrum veritatis! Aliquid quos iure consequuntur voluptate, enim animi labore. Accusantium eos quod, nulla voluptate assumenda doloremque possimus ex ut corrupti veritatis aut. Ut, commodi, nemo voluptatum cum beatae delectus facere, accusantium nulla officia reiciendis eos totam. Doloremque magni suscipit sint. Dolor, ut!</p>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Labore vitae expedita hic illo, deleniti officia quae quo laudantium? Ea modi, illum illo repellendus aspernatur excepturi dolores iusto laborum voluptatem esse, velit laudantium officia optio. Quia officia quaerat ipsam debitis rem odit quis dolorum quae iure, exercitationem rerum vero dolorem magni laborum impedit adipisci soluta facere mollitia reprehenderit nulla molestias sunt delectus quod corporis! Doloremque commodi suscipit est saepe dolor illo quas expedita optio tempora perferendis dolorum ipsam sit, dignissimos necessitatibus aspernatur ullam repellat corporis facere veritatis quod incidunt. Assumenda deleniti repellat nostrum veritatis! Aliquid quos iure consequuntur voluptate, enim animi labore. Accusantium eos quod, nulla voluptate assumenda doloremque possimus ex ut corrupti veritatis aut. Ut, commodi, nemo voluptatum cum beatae delectus facere, accusantium nulla officia reiciendis eos totam. Doloremque magni suscipit sint. Dolor, ut!</p>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Labore vitae expedita hic illo, deleniti officia quae quo laudantium? Ea modi, illum illo repellendus aspernatur excepturi dolores iusto laborum voluptatem esse, velit laudantium officia optio. Quia officia quaerat ipsam debitis rem odit quis dolorum quae iure, exercitationem rerum vero dolorem magni laborum impedit adipisci soluta facere mollitia reprehenderit nulla molestias sunt delectus quod corporis! Doloremque commodi suscipit est saepe dolor illo quas expedita optio tempora perferendis dolorum ipsam sit, dignissimos necessitatibus aspernatur ullam repellat corporis facere veritatis quod incidunt. Assumenda deleniti repellat nostrum veritatis! Aliquid quos iure consequuntur voluptate, enim animi labore. Accusantium eos quod, nulla voluptate assumenda doloremque possimus ex ut corrupti veritatis aut. Ut, commodi, nemo voluptatum cum beatae delectus facere, accusantium nulla officia reiciendis eos totam. Doloremque magni suscipit sint. Dolor, ut!</p>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Labore vitae expedita hic illo, deleniti officia quae quo laudantium? Ea modi, illum illo repellendus aspernatur excepturi dolores iusto laborum voluptatem esse, velit laudantium officia optio. Quia officia quaerat ipsam debitis rem odit quis dolorum quae iure, exercitationem rerum vero dolorem magni laborum impedit adipisci soluta facere mollitia reprehenderit nulla molestias sunt delectus quod corporis! Doloremque commodi suscipit est saepe dolor illo quas expedita optio tempora perferendis dolorum ipsam sit, dignissimos necessitatibus aspernatur ullam repellat corporis facere veritatis quod incidunt. Assumenda deleniti repellat nostrum veritatis! Aliquid quos iure consequuntur voluptate, enim animi labore. Accusantium eos quod, nulla voluptate assumenda doloremque possimus ex ut corrupti veritatis aut. Ut, commodi, nemo voluptatum cum beatae delectus facere, accusantium nulla officia reiciendis eos totam. Doloremque magni suscipit sint. Dolor, ut!</p>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Labore vitae expedita hic illo, deleniti officia quae quo laudantium? Ea modi, illum illo repellendus aspernatur excepturi dolores iusto laborum voluptatem esse, velit laudantium officia optio. Quia officia quaerat ipsam debitis rem odit quis dolorum quae iure, exercitationem rerum vero dolorem magni laborum impedit adipisci soluta facere mollitia reprehenderit nulla molestias sunt delectus quod corporis! Doloremque commodi suscipit est saepe dolor illo quas expedita optio tempora perferendis dolorum ipsam sit, dignissimos necessitatibus aspernatur ullam repellat corporis facere veritatis quod incidunt. Assumenda deleniti repellat nostrum veritatis! Aliquid quos iure consequuntur voluptate, enim animi labore. Accusantium eos quod, nulla voluptate assumenda doloremque possimus ex ut corrupti veritatis aut. Ut, commodi, nemo voluptatum cum beatae delectus facere, accusantium nulla officia reiciendis eos totam. Doloremque magni suscipit sint. Dolor, ut!</p>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Labore vitae expedita hic illo, deleniti officia quae quo laudantium? Ea modi, illum illo repellendus aspernatur excepturi dolores iusto laborum voluptatem esse, velit laudantium officia optio. Quia officia quaerat ipsam debitis rem odit quis dolorum quae iure, exercitationem rerum vero dolorem magni laborum impedit adipisci soluta facere mollitia reprehenderit nulla molestias sunt delectus quod corporis! Doloremque commodi suscipit est saepe dolor illo quas expedita optio tempora perferendis dolorum ipsam sit, dignissimos necessitatibus aspernatur ullam repellat corporis facere veritatis quod incidunt. Assumenda deleniti repellat nostrum veritatis! Aliquid quos iure consequuntur voluptate, enim animi labore. Accusantium eos quod, nulla voluptate assumenda doloremque possimus ex ut corrupti veritatis aut. Ut, commodi, nemo voluptatum cum beatae delectus facere, accusantium nulla officia reiciendis eos totam. Doloremque magni suscipit sint. Dolor, ut!</p>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Labore vitae expedita hic illo, deleniti officia quae quo laudantium? Ea modi, illum illo repellendus aspernatur excepturi dolores iusto laborum voluptatem esse, velit laudantium officia optio. Quia officia quaerat ipsam debitis rem odit quis dolorum quae iure, exercitationem rerum vero dolorem magni laborum impedit adipisci soluta facere mollitia reprehenderit nulla molestias sunt delectus quod corporis! Doloremque commodi suscipit est saepe dolor illo quas expedita optio tempora perferendis dolorum ipsam sit, dignissimos necessitatibus aspernatur ullam repellat corporis facere veritatis quod incidunt. Assumenda deleniti repellat nostrum veritatis! Aliquid quos iure consequuntur voluptate, enim animi labore. Accusantium eos quod, nulla voluptate assumenda doloremque possimus ex ut corrupti veritatis aut. Ut, commodi, nemo voluptatum cum beatae delectus facere, accusantium nulla officia reiciendis eos totam. Doloremque magni suscipit sint. Dolor, ut!</p>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Labore vitae expedita hic illo, deleniti officia quae quo laudantium? Ea modi, illum illo repellendus aspernatur excepturi dolores iusto laborum voluptatem esse, velit laudantium officia optio. Quia officia quaerat ipsam debitis rem odit quis dolorum quae iure, exercitationem rerum vero dolorem magni laborum impedit adipisci soluta facere mollitia reprehenderit nulla molestias sunt delectus quod corporis! Doloremque commodi suscipit est saepe dolor illo quas expedita optio tempora perferendis dolorum ipsam sit, dignissimos necessitatibus aspernatur ullam repellat corporis facere veritatis quod incidunt. Assumenda deleniti repellat nostrum veritatis! Aliquid quos iure consequuntur voluptate, enim animi labore. Accusantium eos quod, nulla voluptate assumenda doloremque possimus ex ut corrupti veritatis aut. Ut, commodi, nemo voluptatum cum beatae delectus facere, accusantium nulla officia reiciendis eos totam. Doloremque magni suscipit sint. Dolor, ut!</p>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Labore vitae expedita hic illo, deleniti officia quae quo laudantium? Ea modi, illum illo repellendus aspernatur excepturi dolores iusto laborum voluptatem esse, velit laudantium officia optio. Quia officia quaerat ipsam debitis rem odit quis dolorum quae iure, exercitationem rerum vero dolorem magni laborum impedit adipisci soluta facere mollitia reprehenderit nulla molestias sunt delectus quod corporis! Doloremque commodi suscipit est saepe dolor illo quas expedita optio tempora perferendis dolorum ipsam sit, dignissimos necessitatibus aspernatur ullam repellat corporis facere veritatis quod incidunt. Assumenda deleniti repellat nostrum veritatis! Aliquid quos iure consequuntur voluptate, enim animi labore. Accusantium eos quod, nulla voluptate assumenda doloremque possimus ex ut corrupti veritatis aut. Ut, commodi, nemo voluptatum cum beatae delectus facere, accusantium nulla officia reiciendis eos totam. Doloremque magni suscipit sint. Dolor, ut!</p>
                </div>
            </section>
        </div>
    )
}

export default ScrollAnimations